### ISSUE TITLE
Does the system support SSO integration? If so, what protocols are supported?

### ISSUE THREAD

**Issue by sx212** [lsfusion/platform#1064]

**Comment by AlexKirkouski** [comment]
lsFusion supports OAuth authentication (unfortunately it is not documented yet, but it will be very soon).

Currently "out of the box" lsFusion supports authentication using the following services / social networks: Facebook, Google, Github, Yandex. In addition, the administrator can add other services by setting the appropriate parameters (Authorization URI, Token URI, etc.). However, you can only add services that work according to a scheme similar to those already supported (since OAuth authentication is a rather abstract standard, and, some social networks for example works according to a different scheme).

**Comment by eratolekov** [comment]
Hi @AlexKirkouski 
Could you please share example project with OAuth (OIDC) authentication?
Or simple plain snippet from your current private project?

**Comment by AlexKirkouski** [comment]
What do you mean under "example project"?

It goes out-of-the-box. Here for example where it is "embedded":
https://demo.lsfusion.org/erp/

You just need to set up some params:
![image](https://github.com/user-attachments/assets/8a1688f6-c5e7-4175-b44a-4adf7a552151)

**Comment by eratolekov** [comment]
It's great. 👍
Thanks a lot!
