### ISSUE TITLE
Add 'duplicate stored property' semantic error

### ISSUE THREAD

**Issue by danchanka** [lsfusion/platform#110]
There is an assertion error when we are trying to call `ImplementTable.addField` with the same name twice. This happens on property initialization step of modules parsing. `CheckDuplicateSystemElementsTask` checks duplicates later, after parsing steps.

![image](https://user-images.githubusercontent.com/20270415/42865230-b33c0728-8a71-11e8-9b80-55b54b3610ca.png)

**Comment by ichavchavadze** [comment]
Already resolved.

```
CLASS Test;
user = DATA CustomUser (Test) NONULL ;
veryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongProp1 (Test t) = user(t) MATERIALIZED;
veryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryLongProp2 (Test t) = user(t) MATERIALIZED;
```

Now is throwing exception 
`Field 'Features_veryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVe' was already added to '_auto_Features_Test' table. The reason might be that the field names are limited in length, and as a result two different canonical names are converted to the same field name due to length truncation. In this case you can either change the property name(s) or change the naming policy (see documentation for details)`

https://github.com/lsfusion/platform/commit/c971dc559dc8540385482c7d88c04efe8dec9f21
