### ISSUE TITLE
desktop-client "Print grid" form toolbar removed in v5, why?

### ISSUE THREAD

**Issue by hernad** [lsfusion/platform#468]
Hi lsfusion developers. 
First, thank you for the great project!

What is the reason (jasper report runSingleGroupReport) this option is removed from master branch.
As I can see, it exists in v3 branch.

Regards,
Ernad

**Comment by AlexKirkouski** [comment]
Well, the reason is that we thought that it was really rear case to use automatic graphical design to print something that is really a data (excel is a lot better for that). So if someone wants to print data he can export this data to excel and print it from there. 

And we got really a lot of questions (because this print button was on-site and everyone wanted to push it) why "we are getting this odd and "ugly" documents".

**Comment by hernad** [comment]
Ok, I understand. That was functional cleanup. 
The goal was to reduce unnecessary customer support issues.
I respect your reasons :)
