### ISSUE TITLE
"columnLabelsWidth" container property error during compilation

### ISSUE THREAD

**Issue by Drunik01** [lsfusion/platform#508]
"columnlabelwidth" container property exists in the documentation, but it doesn't work and the project doesn't compile (tested in version 5)
https://ru-documentation.lsfusion.org/pages/viewpage.action?pageId=4718609

**Comment by AlexKirkouski** [comment]
I'm not so sure what this attribute means in the documentation (caption width is determined automatically, and if there should be some it's customization it should be for component itself, not columns container), and it seems that actually it's not supported. I think, it's better to remove it from the documentation.

**Comment by Drunik01** [comment]
I really miss the alignment of elements like in the picture - I was hoping that "columnlabelwidth" would do it.

![image](https://user-images.githubusercontent.com/12659847/102080011-c3367880-3e1e-11eb-8758-7a03de330981.png)

Now I did it like this:

            MOVE PROPERTY (code(a));
            MOVE PROPERTY (INN(a)){caption='ИНН    ';};
            MOVE PROPERTY (name(a));
            MOVE PROPERTY (ogrn(a)){caption='ОГРН   ';};
            MOVE PROPERTY (kpp(a));
            MOVE PROPERTY (okonx(a));

this is not very convenient

**Comment by AlexKirkouski** [comment]
Yes we know about that problem (aligning captions separately), there will be a new attribute in version 5 called "alignCaptions" (or something like this) for a new TABLE type of a container (instead of columns attribute in CONTAINERV in 4 version). In that case captions will be pulled out (like in TABBED container) and put in a separate column (it's assumed that <table> element will be used for TABLE container type). Of course this TABLE container will be a little bit less flexier than CONTAINER container (essentially flex and base size will be equal) but it's the only way to do it with CSS (when you need to align captions horizontally and vertically simultaneously). Soon there be an article about what is planned in next versions (this article has already been written, just waiting for version 4 release in a week or two I hope), and there will be a little bit more details.

Now the only workaround is to put some extra spaces, which is certainly not very convinient.

**Comment by Drunik01** [comment]
ok, thank you, we will wait it very much
